### ISSUE TITLE
API - stworzenie metod controllerów

### ISSUE THREAD

**Issue by NataliaBakowska** [NataliaBakowska/Car_service#25]
Stworzenie wszystkich niezbędnych metod do przesyłania i odbierania danych w controllerach dla klas Customer, Car i Repair.

W szczególności:
- tworzenie nowego użytkownika/ samochodu / naprawy
- pobranie jednego użytkownika/ samochodu / naprawy po id
- pobranie wszystkich elementów
- wyszukanie wszystkich samochodów danego użytkownika
- wyszukanie napraw danego samochodu 
- logowanie 
- zmiana statusu naprawy

Przewidywany czas: 8h

**Comment by Aroo46** [comment]
Done
