### ISSUE TITLE
(AM) Znalezione błędy i wprowadzenie usprawnień

### ISSUE THREAD

**Issue by Aroo46** [NataliaBakowska/Car_service#32]
(AM) - Aplikacja mobilna
1. Po wprowadzeniu danych do pól tekstowych, klawiatura się nie chowa (ekran logowania, dialog dodawania przypomnień).
2. Po wyjściu z widoku "Historia wypożyczeń" i ponownym wejściu do niego, tekst umieszczony w komórkach wychodzi poza ekran.

Czas pracy 2h.

**Comment by Ukashi93** [comment]
wprowadzenie poprawek 1 i 2
